//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "samey_user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub username: String,
    pub password: String,
    pub is_admin: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::samey_pool::Entity")]
    SameyPool,
    #[sea_orm(has_many = "super::samey_post::Entity")]
    SameyPost,
}

impl Related<super::samey_pool::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SameyPool.def()
    }
}

impl Related<super::samey_post::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SameyPost.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
