//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "samey_pool_post")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub pool_id: i32,
    pub post_id: i32,
    #[sea_orm(column_type = "Float")]
    pub position: f32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::samey_pool::Entity",
        from = "Column::PoolId",
        to = "super::samey_pool::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SameyPool,
    #[sea_orm(
        belongs_to = "super::samey_post::Entity",
        from = "Column::PostId",
        to = "super::samey_post::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SameyPost,
}

impl Related<super::samey_pool::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SameyPool.def()
    }
}

impl Related<super::samey_post::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SameyPost.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
