//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "samey_tag_post")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub tag_id: i32,
    pub post_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::samey_post::Entity",
        from = "Column::PostId",
        to = "super::samey_post::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SameyPost,
    #[sea_orm(
        belongs_to = "super::samey_tag::Entity",
        from = "Column::TagId",
        to = "super::samey_tag::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SameyTag,
}

impl Related<super::samey_post::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SameyPost.def()
    }
}

impl Related<super::samey_tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SameyTag.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
