//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "samey_tag")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    #[sea_orm(unique)]
    pub normalized_name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::samey_tag_post::Entity")]
    SameyTagPost,
}

impl Related<super::samey_tag_post::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SameyTagPost.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
